[formatting]
indent_string = "\t"
reorder_keys = false
reorder_arrays = false
reorder_inline_tables = true

[[rule]]
include = ["**/Cargo.toml"]

[rule.schema]
path = "https://json.schemastore.org/cargo.json"
enabled = true

# schema definition for .cargo/config.toml is not yet available
# see https://github.com/rust-lang/cargo/issues/12883

[[rule]]
include = ["**/Cargo.toml"]
keys = [
	"build-dependencies",
	"dependencies",
	"dev-dependencies",
	"target.*.build-dependencies",
	"target.*.dependencies",
	"target.*.dev-dependencies",
	"workspace.dependencies",
	"workspace.lints.clippy",
]

[rule.formatting]
reorder_keys = true
reorder_arrays = true
reorder_inline_tables = false
