experimental = ["wrapper-scripts"]

[scripts.wrapper.valgrind]
command = [
	'valgrind',
	'--leak-check=full',
	'--errors-for-leak-kinds=definite',
	"--track-fds=yes",
	'--error-exitcode=69',
]

[[profile.default.scripts]]
platform = 'cfg(target_os = "linux")'
run-wrapper = 'valgrind'
